SELECT * FROM [STAGE_1_DB].[SUEZ_TIPPING_SCH_1].[SUEZ_TIPPING_TB_1]

SELECT MIN(DISTINCT [Date]) as EarliestDate,
MAX(DISTINCT [Date]) as LATESTDATE, count(*)
FROM [STAGE_1_DB].[SUEZ_TIPPING_SCH_1].[SUEZ_TIPPING_TB_1]


SELECT MIN(DISTINCT [Date]) as EarliestDate,
MAX(DISTINCT [Date]) as LATESTDATE, count(*)
FROM [STAGE_2_DB].[SUEZ_TIPPING_SCH_2].[SUEZ_TIPPING_TB_2]

-- When clone a table
-- SELECT *
-- INTO ABC_1
-- FROM ABC;

WITH DistinctDockets AS
(
    SELECT * ,
        ROW_NUMBER() OVER(
            PARTITION BY [Docket] ORDER BY [Docket]) AS 'RowNum' 
    FROM [STAGE_1_DB].[SUEZ_TIPPING_SCH_1].[SUEZ_TIPPING_TB_1]
    -- WHERE [Date] >= '20210324'
    -- AND [Date] <= '20210406'
)
SELECT * INTO #TmpTB
FROM DistinctDockets
WHERE RowNum = 1;


ALTER TABLE #TmpTB
DROP COLUMN [RowNum], [ID]

INSERT INTO [STAGE_2_DB].[SUEZ_TIPPING_SCH_2].[SUEZ_TIPPING_TB_2]
SELECT * FROM #TmpTB
DROP TABLE #TmpTB

