SELECT * FROM [STAGE_1_DB].[SUEZ_TIPPING_SCH_1].[SUEZ_TIPPING_TB_1];

SELECT MIN(DISTINCT [Date]) as EarliestDate,
MAX(DISTINCT [Date]) as LATESTDATE, count(*)
FROM [STAGE].[SUEZ_TIPPING_SCH_1].[SUEZ_TIPPING_TB_1];

SELECT MIN(DISTINCT [Date]) as EarliestDate,
MAX(DISTINCT [Date]) as LATESTDATE, count(*)
FROM [STAGE].[SUEZ_TIPPING_SCH_2].[SUEZ_TIPPING_TB_2];


WITH DistinctDockets AS
(
    SELECT * ,
        ROW_NUMBER() OVER(
            PARTITION BY [Docket] ORDER BY [Docket]) AS 'RowNum' 
    FROM [STAGE].[SUEZ_TIPPING_SCH_1].[SUEZ_TIPPING_TB_1]
    WHERE [DATE] > '20211028'
    -- BETWEEN '20211007' AND '20211028'
    
)
SELECT * INTO #TmpTB
FROM DistinctDockets
WHERE RowNum = 1;

ALTER TABLE #TmpTB
DROP COLUMN [RowNum], [ID]


INSERT INTO [STAGE].[SUEZ_TIPPING_SCH_2].[SUEZ_TIPPING_TB_2]
SELECT * FROM #TmpTB
DROP TABLE #TmpTB



SELECT DISTINCT count([Docket]) FROM [STAGE].[SUEZ_TIPPING_SCH_2].[SUEZ_TIPPING_TB_2]

-- new suez table

-- SELECT * INTO 
-- [STAGE].[SUEZ_TIPPING_SCH_2].[SUEZ_TIPPING_TB_2]
-- FROM #TmpTB
-- DROP TABLE #TmpTB
